name: apidocs
on:
  pull_request:
    branches:
      - master
      - release-candidate
      - release
jobs:
  lint:
    runs-on: ubuntu-22.04
    timeout-minutes: 10

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      # https://github.com/actions/checkout/releases/tag/v4.0.0
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac
      - name: Use Node.js ${{ matrix.node-version }}
        # https://github.com/actions/setup-node/releases/tag/v4.0.0
        uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci

      # We use the config module to configure the apidocs generation
      - name: Create config module
        run: cp ./config.js.template ./src/config.js

      - name: Create the tmp folder
        run: mkdir tmp

      # Generating the apidocs json and linting
      - name: Create the apidocs json
        run: npm run docs_convert
      - name: Lint the apidocs json
        run: npm run docs_lint
