name: lint
on:
  push:
    branches:
      - master
      - dev
    tags:
      - v*
  pull_request:
    branches:
      - dev
      - master

jobs:
  test:
    runs-on: "ubuntu-latest"
    timeout-minutes: 10
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      # https://github.com/actions/checkout/releases/tag/v2.7.0
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5
      - name: Use Node.js ${{ matrix.node-version }}
        # https://github.com/actions/setup-node/releases/tag/v1.4.6
        uses: actions/setup-node@f1f314fca9dfce2769ece7d933488f076716723e
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint
