name: lint
on:
  push:
    branches:
      - master
      - dev
    tags:
      - v*
  pull_request:
    branches:
      - dev
      - master

jobs:
  test:
    runs-on: "ubuntu-latest"
    timeout-minutes: 10
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      # This file is required by most controllers and triggers "import/no-unresolved" if missing
      - name: Copy config file
        run: cp ./__tests__/integration/configuration/config-fixture.js ./src/config.js

      - name: Lint
        run: npm run lint
