name: lint
on:
  push:
    branches:
      - master
      - release-candidate
      - release
    tags:
      - v*
  pull_request:
    branches:
      - master
      - release-candidate
      - release

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        node-version: [22.x]
    steps:
      # https://github.com/actions/checkout/releases/tag/v4.1.7
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
      - name: Use Node.js ${{ matrix.node-version }}
        # https://github.com/actions/setup-node/releases/tag/v4.0.3
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint
